### Stage 1: Build ###
FROM node:18.12-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

### Stage 2: Run ###
FROM nginx:1.22-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/term-mi-familia /usr/share/nginx/html
